ALTER TABLE service_jobs
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE inventory_items
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE manual_expenses
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE cashflow_summary
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE allowance_withdrawals
ADD COLUMN IF NOT EXISTS legacy_source_id TEXT,
ADD COLUMN IF NOT EXISTS sheet_row_number INTEGER,
ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS sync_dirty BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sync_source TEXT NOT NULL DEFAULT 'sheet',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_service_jobs_sync_dirty ON service_jobs(sync_dirty);
CREATE INDEX IF NOT EXISTS idx_inventory_items_sync_dirty ON inventory_items(sync_dirty);
CREATE INDEX IF NOT EXISTS idx_clients_sync_dirty ON clients(sync_dirty);
CREATE INDEX IF NOT EXISTS idx_manual_expenses_sync_dirty ON manual_expenses(sync_dirty);
CREATE INDEX IF NOT EXISTS idx_cashflow_summary_sync_dirty ON cashflow_summary(sync_dirty);
CREATE INDEX IF NOT EXISTS idx_allowance_withdrawals_sync_dirty ON allowance_withdrawals(sync_dirty);
